apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresspool-machine
  namespace: metallb-system
spec:
  addresses:
  - 172.16.28.180-172.16.28.184
  autoAssign: true
  avoidBuggyIPs: false